### ISSUE TITLE
Improve eden reconfig workflow

### ISSUE THREAD

**Issue by eriknordmark** [lf-edge/eden#289]
A common usage I have for eden is to validate onboarding and other early stages while I test different images I've built and tagged locally (make eve in the eve repo produces a tag which I feed to eden).

While that has improved, it is still painful and if I don't do the ./eden cleanup before the ./eden stop it creates a mess and the easiest is to rm -rf and clone the eden repo again, which takes a long time.

What I would like to do is just an initial setup of the form
            ./eden config add default
            ./eden config set default --key eve.tag --value tag1
            ./eden setup
            ./eden start
            ./eden eve onboard
run some tests

and then be able to do repeated updates of the tag/image using something like this:
            ./eden config set default --key eve.tag --value tag2
            ./eden eve offboard
            ./eden restart
            ./eden eve onboard
so I can re-run the tests

**Comment by giggsoff** [comment]
Hi, @eriknordmark .
Eden doing "offboard" during `./eden clean` (removes onboard and device certs from Adam). You do not need to do rm -rf (actually, it may broke process, cause it deletes certs for previously deployed Adam, which uses docker volume), because eden deletes files automatically.
Can you please elaborate more information about problems with `./eden clean`? Maybe with debug (`./eden clean -v debug`).

Another note (we should clarify this point in the readme): with `make eve` you build something like `lfedge/eve:0.0.0-test-12345678-xen-amd64`. You need to feed into `eden`:
`./eden config set default --key eve.tag --value 0.0.0-test-12345678`
`./eden config set default --key eve.hv --value xen`  <- default one is `kvm` here

**Comment by eriknordmark** [comment]
Eden clean used to fail (and not clean up) if I had already done a stop. See other issue agaist Adam from a week ago.
Sounds like that is fixed.

It is somewhat assymetric to have clean be the opposite of onboard plus other stuff, and not have an explicit offboard (which clean could invoke). That makes it harder to understand.

Restart would be a convience. I haven't managed to fat finger eden into some broken state in the last few days, but I've been using it daily as well. If I don't do that I might forget the magic sequence.

Documenting the tag or even better have eden extract the hv from the tag would make it easier for newcomers.

**Comment by eriknordmark** [comment]
Just checked and ./eden clean only does an offboard in some cases.
If I remember to do ./eden stop before clean it does an offboard.
Otherwise ./eden clean ends with
2020/10/03 00:05:30 Cannot parse Device UUID uuid: incorrect UUID length: Bad
and the certificates are not cleaned up.

Here is the sequence I did:
nordmark@bobo:~/master/eden$ ./eden stop
INFO[0000] adam stopped                                 
INFO[0000] redis stopped                                
INFO[0001] registry stopped                             
INFO[0001] eserver stopped                              
INFO[0001] EVE stopped                                  
nordmark@bobo:~/master/eden$ ./eden clean
INFO[0000] Cleanup current context                      
INFO[0000] started container: 39556f3362bc95ad8a77610aa47d738920ba6afa0e07f1890123b100fe280c6d 
INFO[0000] Redis is running and accessible on port 6379 
INFO[0000] started container: fbaae8315b7114e1d8ff0b89635bddde75608c02fd51ad44c2c2643120d216c0 
INFO[0000] Adam is running and accessible on port 3333  
2020/10/03 00:05:30 Cannot parse Device UUID uuid: incorrect UUID length: Bad
nordmark@bobo:~/master/eden$ ./eden config set default --key eve.tag --value 0.0.0-emerg-100146ae-dirty-2020-10-02.08.21
INFO[0000] Current context is: default                  
nordmark@bobo:~/master/eden$ ./eden setup
INFO[0000] Config file /home/nordmark/.eden/contexts/default.yml is the same as /home/nordmark/master/eden/dist/default-config_saved.yml 
INFO[0000] Certs already exists in certs dir: /home/nordmark/master/eden/dist/default-certs 
INFO[0000] GenerateEVEConfig done                       
INFO[0000] EVE already exists in dir: /home/nordmark/master/eden/dist/default-images/eve

**Comment by mydatascience** [comment]
Do we still have this issue @eriknordmark  or I can close it?
