### ISSUE TITLE
eden config generates incorrect eden.root

### ISSUE THREAD

**Issue by rvs** [lf-edge/eden#47]
My eden workspace is checked out at `/Users/roman/src/lfe/eden` however when I run `eden config` I see that the value of eden.root is pointing to `/Users/roman/eden`

**Comment by sadov** [comment]
Fixed at [PR50](https://github.com/lf-edge/eden/pull/50)

**Comment by mydatascience** [comment]
Likely not fixed. Eden config still tries to put config to /home/fleandr/.eden/ if I run from ~/eden2/eden

**Comment by rvs** [comment]
Can we please get a resolution here @sadov @giggsoff ?

**Comment by mydatascience** [comment]
I suggest to put /.eden/ in the current eden directory instead of home

**Comment by mydatascience** [comment]
close? @rvs
